export const smallBox = {
  position: "relative",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 500,
  borderRadius: "5px",
  outline: "none",
  background: "white",
  overflow: "clip",
  fontSize: "15px",
};
export const xSmallBox = {
  position: "relative",
  top: "50%",
  left: "58.3%",
  transform: "translate(-50%, -50%)",
  width: 350,
  borderRadius: "5px",
  outline: "none",
  background: "white",
  overflow: "clip",
  fontSize: "15px",
};
export const xMediumBox = {
  position: "relative",
  top: "50%",
  left: "58.3%",
  transform: "translate(-50%, -50%)",
  width: 450,
  borderRadius: "5px",
  outline: "none",
  background: "white",
  overflow: "clip",
  fontSize: "15px",
};
export const normalBox = {
  position: "relative",
  top: "50%",
  left: "58.3%",
  transform: "translate(-50%, -50%)",
  width: 500,
  borderRadius: "5px",
  outline: "none",
  background: "white",
  overflow: "clip",
  fontSize: "15px",
};
export const wideBox = {
  position: "relative",
  top: "50%",
  left: "58.3%",
  transform: "translate(-50%, -50%)",
  width: 700,
  borderRadius: "5px",
  outline: "none",
  background: "white",
  overflow: "clip",
  fontSize: "15px",
};
export const widerBox = {
  position: "relative",
  top: "50%",
  left: "58.3%",
  transform: "translate(-50%, -50%)",
  width: 1000,
  borderRadius: "5px",
  outline: "none",
  background: "white",
  overflow: "clip",
  fontSize: "15px",
};
